#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
day=$(date +"%d.%m.%y")

todays_file=$(find $SCRIPT_DIR/sessions/ -name $day)
if [[ -z $todays_file ]]; then
  touch "$SCRIPT_DIR/sessions/$day"
  todays_file=$(find $SCRIPT_DIR/sessions/ -name $day)
fi 


# TODO: every file should be a date of this format and should store every session
printf "day: $day\n"

cleanup() {
  if [[ -n $minutes ]]; then
    printf "\n\nTimer Closed! Start a new one now.\n"
  fi

  if [[ -n $tloop_pid ]]; then
    kill "$tloop_pid"
  fi
}
trap cleanup EXIT

initial_prompt() {
  SUFFIX=".. minutes"

  printf "timer for %s" "$SUFFIX"

  tput cub "${#SUFFIX}"

  read -r minutes
  if [ -z $minutes ]; then
    printf "\nERROR: Empty Input\n"
    exit 1
  fi
  echo $minutes > $todays_file
}

read_input() {
  pause=
  read -sn 1 pause

  if [ "$pause" = "p" ] 
    then
      t=$(cat $todays_file)
      kill "$tloop_pid"
      tloop_pid=
      printf "\n\nPAUSED AT $t! Press 's' to start."

      start=
      read -sn 1 start
      if [ "$start" = "s" ]
      then
        printf "\n\nStarting...\n"
        beg
      fi
  fi
}

tloop() {
  t=$(cat $todays_file)
  printf "\n"
  printf "\r$t minutes left"
  while [ $t -gt 0 ]; do
    sleep 60
    let "t-=1"
    text="$t minutes left"
    printf "\r$text"
    echo $t > $todays_file
  done

  printf "\nPress Enter to Close\n"
  paplay $SCRIPT_DIR/assets/sound.wav
  while sleep 3; do
    printf "Press Enter to Close\n"
  done
}

beg() {
  if [[ -n $tloop_pid ]]; then
    kill "$tloop_pid"
    tloop_pid=
  fi
  tloop_pid=
  tloop&
  tloop_pid=$!

  read_input
}

initial_prompt

beg
